name: google_fonts
description: A dummy replacement for google_fonts to prevent AssetManifest crashes.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
